Download complete dossier
Amsterdam/data-verkenner pull request #4352
Opened 2021-06-10 08:45 UTC by thomasm0

This feature introduces the following changes to the Construction Dossier Pages:
- A download all button ('Download geheel dossier')
- A checkbox to toggle all documents in Document Details
- If the download all button is used but the user does not have rights to view all Documents, a new modal (RestrictedFilesModal) appears before the Download modal listing the excluded files.

- 7537 Downloaden volledig dossier

2021-06-10 08:50 UTC, thomasm0 commented on src/app/pages/ConstructionDossierPage/components/DocumentDetails/DocumentDetails.test.tsx
> +  it('checking the select all checkbox updates the label accordingly', () => {
With this test - initially I would have like to tested if all the Document checkboxes are checked, however, in this test the FilesGallery component uses a mock component. If you include the real component there's quite a few console warnings from FilesGallery - "Warning: An update to IIIFThumbnail inside a test was not wrapped in act". It's not breaking but certainly not very clean.

I've seen similar warnings with the download modal (it seems to attempt API requests in tests) but didn't identify an easy fix. I'll continue exploring but it doesn't seem a major issue.

2021-06-10 08:52 UTC, thomasm0 commented on src/app/pages/ConstructionDossierPage/components/DossierDetails/DossierDetails.test.tsx
> +const VALID_DECODED_TOKEN: DecodedToken = {
Would be nice to move this valid token handling to a shared util as it's also used in AuthTokenContext

2021-06-10 13:38 UTC, jonkoops commented on src/app/pages/ConstructionDossierPage/components/DossierDetails/DossierDetails.test.tsx
> +const VALID_DECODED_TOKEN: DecodedToken = {
Yeah for sure, although making tests DRY is not really that big of an issue for me.

2021-06-14 11:59 UTC, jonkoops requested changes

2021-06-14 11:59 UTC, jonkoops commented on src/app/pages/ConstructionDossierPage/components/RestrictedFilesModal/RestrictedFilesModal.tsx
> +  const fileList = files.map(({ filename, url }) => <ListItem key={url}>{filename}</ListItem>)
Since this variable is only used once, why not inline this logic in the `<List>`?

2021-06-14 11:59 UTC, jonkoops commented on src/app/pages/ConstructionDossierPage/components/RestrictedFilesModal/RestrictedFilesModal.tsx
> +          <List variant="bullet">{fileList}</List>
This list can be quite long depending on the dossier, perhaps this is something we should check the worst case scenario of to see if the UX still holds up.

2021-06-14 11:59 UTC, jonkoops commented on src/app/pages/ConstructionDossierPage/components/DossierDetails/DossierDetails.tsx
> +  const [currentModal, setCurrentModal] = useState<string | null>(null)
It could be a good idea to keep a type for all possible modals types. For example:

```ts
export type ModalType = 'login' | 'select' | 'download' | 'restricted'

const [currentModal, setCurrentModal] = useState<ModalType | null>(null)
```

This will prevent typos from sneaking in which might cause bugs. For example, `setCurrentModal('ownload') ` would produce an error when compiling since it's not a valid value.

2021-06-14 11:59 UTC, jonkoops commented on src/app/pages/ConstructionDossierPage/components/DossierDetails/DossierDetails.tsx
> +  const hasRights = useMemo(() => {
Since `restricted` is only used to determine `hasRights` perhaps the logic for it can be moved into this `useMemo`.

2021-06-14 11:59 UTC, jonkoops commented on src/app/pages/ConstructionDossierPage/components/DossierDetails/DossierDetails.tsx
> +  const hasRights = useMemo(() => {
On a sidenote, this logic is now duplicated between `DossierDetails` and `DocumentDetails`, perhaps we can put it in a seperate hook somehow and re-use it?

2021-06-14 11:59 UTC, jonkoops commented on src/app/pages/ConstructionDossierPage/components/DossierDetails/DossierDetails.tsx
> +      setRestrictedDownloadFiles(files)
This is the only place this value is set, which makes me suspect this could also be a computed value using `useMemo`.

```ts
const restrictedFiles = useMemo(() => {
  // Logic to determine restricted files here.
}, [])
```

2021-06-14 11:59 UTC, jonkoops commented on src/app/pages/ConstructionDossierPage/components/DossierDetails/DossierDetails.tsx
> +      .filter((doc) => {
Perhaps it would be a good idea to extract this logic into a function that can be re-used throughout the component. For example:

```ts
function hasAccess(scopes: string[], access: BouwdossierAccess) {
  if (access === 'PUBLIC') {
    return true
  }

  return scopes.includes(SCOPES['BD/X']) 
}
```

This should make it easier to use later on, for example:

```ts
const files = dossier.documenten
  .filter((doc) => hasAccess(scopes, doc.access))
  .map((doc) => doc.bestanden)
  .flat()
```

2021-06-14 13:47 UTC, thomasm0 commented on src/app/pages/ConstructionDossierPage/components/RestrictedFilesModal/RestrictedFilesModal.tsx
> +          <List variant="bullet">{fileList}</List>
Agreed, I did a quick check to see what happens if there are more list items than the modal's max-height (75%) and it becomes scrollable - it's not the most intuitive in terms of UX but I think it's sufficient.

2021-06-14 14:22 UTC, thomasm0 commented on src/app/pages/ConstructionDossierPage/components/DossierDetails/DossierDetails.tsx
> +  const [currentModal, setCurrentModal] = useState<string | null>(null)
This is awesome! I briefly looked at string enums thinking this was possible somehow but I guess I got distracted/took the easy String option. Thanks!

2021-06-14 14:27 UTC, chrisvanmook commented on src/app/pages/ConstructionDossierPage/components/DocumentDetails/DocumentDetails.tsx
> +    left: 12px;
you could use `themeSpacing(3)` here (3 * 4 = 12px), for consistency sakes :)

2021-06-14 14:27 UTC, chrisvanmook commented on src/app/pages/ConstructionDossierPage/components/DocumentDetails/DocumentDetails.tsx
> +  const [allFilesSelected, setAllFilesSelected] = useState(false)
I believe we could introduce a derived state with `useMemo` from `selectedFiles` from this, instead of having to set it's own state.

2021-06-16 09:08 UTC, chrisvanmook approved these changes

2021-06-16 10:25 UTC, merged