WIP: Feature/scss autosuggest refactor
Amsterdam/data-verkenner pull request #4575
Opened 2021-08-12 14:45 UTC by lpsmitamsterdam

2021-08-13 09:52 UTC, lpsmitamsterdam commented on src/app/components/Header/auto-suggest/AutoSuggest.tsx
> +  color: ${themeColor('tint', 'level5')}; //was $secondary-gray60 !note not the same but closest;
@chrisvanmook @thomasm0 how shall we approach the mismatch between colors in the sass theme and the asc? should we maybe refine this together with design?

2021-08-16 08:00 UTC, chrisvanmook commented on src/app/components/Header/auto-suggest/AutoSuggest.tsx
> +  color: ${themeColor('tint', 'level5')}; //was $secondary-gray60 !note not the same but closest;
as discussed, let's leave it for now, we can create another ticket and PR's to fix this and allign with design

2021-08-16 08:17 UTC, chrisvanmook commented on src/app/components/Header/auto-suggest/AutoSuggestItem.tsx
> +  &--active {
is `--active` being used anywhere?

2021-08-16 08:17 UTC, chrisvanmook approved these changes

2021-08-16 09:00 UTC, lpsmitamsterdam commented on src/app/components/Header/auto-suggest/AutoSuggestItem.tsx
> +  &--active {
good you mention this actually, as useTraverselist & headersearch refer to the active class so i have to fix that as the classname has changed

2021-08-16 09:14 UTC, thomasm0 requested changes
Everything looks good except for the AutoSuggestDropdown 45px instead of 40px

2021-08-16 09:14 UTC, thomasm0 commented on src/app/components/Header/auto-suggest/AutoSuggest.tsx
> +    top: 45px; // This is the height of the SearchBarMenu from @amsterdam/asc-ui
I noticed 5px more top spacing in this version than compared to production. On production this media-query only applies the styling `max-width: calc(100% - 45px)`

2021-08-16 14:40 UTC, thomasm0 approved these changes

2021-08-16 14:40 UTC, merged