Feature/23373 searchbar
Amsterdam/data-verkenner pull request #4861
Opened 2021-11-11 09:17 UTC by lpsmitamsterdam

2021-11-11 11:28 UTC, chrisvanmook commented on src/shared/components/SearchBarNew/SearchBarNew.tsx
> +  onBlur: () => void
I think you can leave `value` and `onBlur` out of this, as it's already coming from `HTMLInputElement`

2021-11-11 11:28 UTC, chrisvanmook commented on src/shared/components/Header/HeaderSearchNew.tsx
> +const ACTIVE_ITEM_CLASS = 'auto-suggest__dropdown-item--active'
Do we still need this? Seems like an obsolete scss class

2021-11-18 17:42 UTC, chrisvanmook commented
Looking good! I've noticed that the arrows (when traversing through the results) do not work yet. Also, we don't need to call this "new" anymore, you're allowed to refactor the existing component :)

2021-11-24 10:53 UTC, lpsmitamsterdam commented on src/shared/components/Header/HeaderSearchNew.tsx
> +const ACTIVE_ITEM_CLASS = 'auto-suggest__dropdown-item--active'
yeah we need it, its used to style the active element in the autosuggest

2021-11-24 16:08 UTC, chrisvanmook requested changes

2021-11-24 16:08 UTC, chrisvanmook commented on src/pages/MapPage/components/DetailPanel/DetailItem.tsx
> -      {item.title && !hideHeader && (
What does this have to do with the searchbar?

2021-11-24 16:08 UTC, chrisvanmook commented on src/shared/components/Header/AutoSuggest/AutoSuggest.tsx
> +  padding-bottom: 10px * 0.5;
What are these funky calculations? 😂  Legacy stuff I guess? Please have a look at the current `AutosuggestDropDown`, I've modified some styles there, I honestly think you can remove / replace some styles here

2021-11-24 16:08 UTC, chrisvanmook commented on src/shared/components/Header/AutoSuggest/AutoSuggest.tsx
> +  padding: 0 16px;
Could use `themeSpacing` here

2021-11-24 16:08 UTC, chrisvanmook commented on src/shared/components/Header/AutoSuggest/AutoSuggest.tsx
> +          <SkeletonWrapper>
Whoop!

2021-11-24 16:08 UTC, chrisvanmook commented on src/shared/components/Header/AutoSuggest/AutoSuggestCategory.tsx
> +    padding-top: 12px;
themeSpacing here

2021-11-24 16:08 UTC, chrisvanmook commented on src/shared/components/Header/AutoSuggest/AutoSuggestCategory.tsx
> +const AutoSuggestDropdownCategoryHeading = styled.h6`
again have a look at the current `AutoSuggestDropdownCategoryHeading`, replaced some styles and values

2021-11-24 16:08 UTC, chrisvanmook commented on src/shared/components/Header/AutoSuggest/AutoSuggestItem.tsx
> +  padding-bottom: calc(${10 / 2}px); // was $base-whitespace
Can be replaced with themeSpacing

2021-11-24 16:08 UTC, chrisvanmook commented on src/shared/components/Header/AutoSuggest/AutoSuggestItem.tsx
> +  color: #000; // was $primary-dark
use themeColor here

2021-11-24 16:08 UTC, chrisvanmook commented on src/shared/components/Header/AutoSuggest/AutoSuggestItem.tsx
> +  &.auto-suggest__dropdown-item--active {
legacy style or not?

2021-11-24 16:08 UTC, chrisvanmook commented on src/shared/components/SearchBar/SearchBar.tsx
> +  right: 36px;
is there perhaps a way we can position this with flexbox?

2021-11-25 10:58 UTC, lpsmitamsterdam commented on src/pages/MapPage/components/DetailPanel/DetailItem.tsx
> -      {item.title && !hideHeader && (
good point

2021-11-25 10:59 UTC, lpsmitamsterdam commented on src/pages/MapPage/components/DetailPanel/DetailItem.tsx
> -      {item.title && !hideHeader && (
good point, putting it back

2021-11-25 11:33 UTC, lpsmitamsterdam commented on src/shared/components/Header/AutoSuggest/AutoSuggestItem.tsx
> +  &.auto-suggest__dropdown-item--active {
nope need it for the active styling

2021-11-25 11:59 UTC, lpsmitamsterdam commented on src/shared/components/SearchBar/SearchBar.tsx
> +  right: 36px;
not quite sure because it needs to lay on top of the input element. We could opt for the native clear button by using type="search" on the input and override those styles?

2021-11-30 09:31 UTC, thomasm0 approved these changes

2021-12-01 11:54 UTC, merged