Feature/cypressimproved
Amsterdam/data-verkenner pull request #4985
Opened 2021-12-14 10:53 UTC by jeswaran2021

Updated Cypress script added for the New homepage, Static page content, accessibility check on the page.

2021-12-15 09:20 UTC, chrisvanmook requested changes

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/accessibility/homePageaccessibility.ts
> +        // eslint-disable-next-line cypress/no-unnecessary-waiting
I think we can remove the eslint-disable comments here

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/newhomePage/newhomePage-links.ts
> +/* eslint-disable cypress/no-unnecessary-waiting */
I think we should remove these eslint-disable comments

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/newhomePage/newhomePage-links.ts
> +      it('should have href link in the homepage content ', () => {
Basically you also test if all the underlying pages are rendered properly. Shouldn't this be part of a smoketest?

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/newhomePage/newhomePage-searchtext.ts
> +/* eslint-disable @typescript-eslint/no-unused-vars */
Again, we should only disable lint rules when absolutely necessary

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/newhomePage/newhomePage-searchtext.ts
> +        cy.get('input').type(SEARCH.autoDropsearchtext, { delay: 80 }).tab().tab().click()
Why do we need the arbitrary delay of 80 in all of the tests?

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/plugins/index.ts
>  // eslint-disable-next-line @typescript-eslint/no-var-requires,import/no-import-module-exports
Remove lint comment

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/regressionSuite/homePage-componentheaderlink.ts
> +  describe('Onderdelen module in Homepage, without authenticated', () => {
"in Homepage" is redundant here

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/regressionSuite/homePage-componentheaderlink.ts
> +      it('should have link to the Panoramic in header ', () => {
Panoramic -> panorama-viewer

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/regressionSuite/homePage-componentheaderlink.ts
> +  describe.only('As loggedin', () => {
The `.only` will skip the other tests

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/regressionSuite/staticPage-colofonfooterlink.ts
> +/* eslint-disable cypress/no-unnecessary-waiting */
Remove eslint comment

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/regressionSuite/staticPage-helpheaderlink.ts
> -        // eslint-disable-next-line cypress/no-unnecessary-waiting
Remove eslint comment

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/regressionSuite/staticPage-helpheaderlink.ts
> -        cy.wait(3000)
We should not wait an arbitrary 3000 ms here

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/regressionSuite/staticPage-overoisheaderlink.ts
> +/* eslint-disable cypress/no-unnecessary-waiting */
Remove eslint comment

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/regressionSuite/staticPage-overoisheaderlink.ts
> +/// <reference types="cypress-downloadfile"/>
Do we need this comment?

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/regressionSuite/staticPage-overoisheaderlink.ts
> +      it('should have link to the about ris', () => {
Typo: ris -> ois

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/regressionSuite/staticPage-overoisheaderlink.ts
> +        cy.get(FOOTERSIDEBARLINK.aboutoisSidebar).click({ force: true })
Why do we need `{ force: true }` here?

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/smokeSuite/homePage-colofonfooterlink.ts
> +/* eslint-disable cypress/no-unnecessary-waiting */
Remove eslint comment

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/smokeSuite/homePage-componentheaderlink.ts
> +/* eslint-disable cypress/no-unnecessary-waiting */
Remove eslint comment

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/smokeSuite/homePage-helpheaderlink.ts
> +/* eslint-disable cypress/no-unnecessary-waiting */
Remove eslint comment

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/smokeSuite/homePage-overoisheaderlink.ts
> +/* eslint-disable @typescript-eslint/restrict-template-expressions */
Remove eslint comment

2021-12-15 09:20 UTC, chrisvanmook commented on cypress/smokeSuite/homePage-overoisheaderlink.ts
> +      it('should have link to the about ris', () => {
Typo

2021-12-16 11:16 UTC, thomasm0 approved these changes

2021-12-16 11:16 UTC, thomasm0 commented on cypress/support/selectorsConstant.ts
> +/* eslint-disable prettier/prettier */
I'm a bit confused with some of the objects in this file. Some are links selectors, some are link labels/text and some are link URLs. Some look duplicated but it's difficult to figure out from the naming and key-values if it is a duplicate or different element/link.

We also have a file `cypress/support/selectors.ts` so I'm a bit confused to the difference between these files.

I've tried to clean things up a bit by appending `_ELEMENTS` `_LINKS` `_ URLS`  to the constant names so in future it's easier to gues what the constant is but I wasn't sure about some.

2021-12-16 11:16 UTC, thomasm0 commented on cypress/support/selectorsConstant.ts
> +export const CONTENT_LINKS = {
This object has values that are labels and selectors. `CONTENT_LINKS` is also a bit vague - when we add tests for other pages I imagine this list will become quite difficult to maintain.

2021-12-16 11:16 UTC, thomasm0 commented on cypress/support/selectorsConstant.ts
> +export const ABOUT_OIS_DROPDOWN_SELECTORS = {
I assumed that this is the About OIS dropdown links in the header navigation menu but there's more links here than there is in the dropdown.

2021-12-16 11:16 UTC, thomasm0 commented on cypress/support/selectorsConstant.ts
> +export const FOOTER_SIDEBAR_LINKS = {
I think these are shared links between the footer and sidebar? It's a bit confusing as we also have `SIDEBAR_URLS`, `FOOTER_LINK_URLS` and other `FOOTER_` objects. If more pages are added this may also become difficult to maintain.

2021-12-16 11:16 UTC, thomasm0 commented on cypress/support/selectorsConstant.ts
> +export const MAP_LAYERS = {
I would define this object as `MAP_LAYER_CHECKBOXES` because`MAP_LAYERS` is a bit vague and I think will grow as more tests are added.

2021-12-16 11:16 UTC, thomasm0 commented on cypress/support/selectorsConstant.ts
> +export const SEARCH = {
`SEARCH_ELEMENTS` seems logical but I wasn't sure if all the properties are actually related to search page elements (for example - `autoDropdownsearchText`, `autoDropdownsearchmatchtext` - we should also ensure that we use proper camelcase naming for easier readability - so things like `autoDropdownsearchmatchtext` --> `autoDropdownSearchMatchText`)

2022-01-12 15:11 UTC, lpsmitamsterdam commented on cypress/integrationNew/mobileviewsmokeSuite/mobileviewhomePage-componentheaderlink.ts
> +      it('should have a link to the panorama-viewer page in header ', () => {
the title of the test is wrong here

2022-01-17 15:41 UTC, thomasm0 commented on cypress/integrationNew/accessibilitySuite/homePage.ts
> +        cy.get('input').type(SEARCH.autoDropsearchtextwithenter, { delay: 80 })
I'm a little confused to what this constant is via the naming. This should also be proper camelcase; for example: `SEARCH.autoDropSearchTextWithEnter`.

2022-03-03 10:59 UTC, closed without merging