Feature/ondergrond dossier
Amsterdam/data-verkenner pull request #5143
Opened 2022-01-27 16:01 UTC by thomasm0

2022-01-28 09:23 UTC, lpsmitamsterdam requested changes

2022-01-28 09:23 UTC, lpsmitamsterdam commented on src/pages/static/UndergroundDossierPage/components/Intro/Intro.tsx
> +  margin: 0 ${themeSpacing(4)};
I think the paragraph shouldnt have horizontal margin to align with the h1 on desktop

2022-01-28 09:23 UTC, lpsmitamsterdam commented on src/pages/static/UndergroundDossierPage/components/Intro/Intro.tsx
> +  margin: 0 ${themeSpacing(4)};
<img width="217" alt="Schermafbeelding 2022-01-28 om 10 05 36" src="https://user-images.githubusercontent.com/88381082/151518396-2f413402-692c-4e52-bf90-b1d83efc3d52.png">

2022-01-28 09:23 UTC, lpsmitamsterdam commented on src/pages/static/UndergroundDossierPage/components/Intro/Intro.tsx
> +  background-color: #fafafa;
replace with asc variable?

2022-01-31 09:03 UTC, thomasm0 commented on src/pages/static/UndergroundDossierPage/components/Intro/Intro.tsx
> +  background-color: #fafafa;
The closest ASC color is `#F5F5F5` which is a little darker than the design's `#FAFAFA`

2022-01-31 10:50 UTC, lpsmitamsterdam approved these changes

2022-01-31 10:52 UTC, merged